### ISSUE TITLE
Error for column 'UUID' when using MySQL

### ISSUE THREAD

**Issue by Guhenriques** [Artillex-Studios/AxPlayerWarps#3]
Hey, I've enabled mysql and now i'm having this issue whenever a player joins.

Running latest version 1.0.2 on Purpur - Minecraft version 1.21.1

```
[13:06:52 INFO]: UUID of player XXXX is 6ab0f8ba-0fd5-4452-86ae-4fd30542[...]
com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'uuid' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:95)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.database.impl.Base.insert(Base.java:191)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getPlayerId(Base.java:216)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getPlayerId(Base.java:203)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getFavoriteWarps(Base.java:658)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.user.WarpUser.lambda$new$0(WarpUser.java:30)
        at AxPlayerWarps-1.0.2.jar//com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Yukino12333** [comment]
I'm getting this issue as well, please fix it
`[11:49:34 WARN]: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'uuid' at row 1
[11:49:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
[11:49:34 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.libs.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.libs.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.database.impl.Base.insert(Base.java:191)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getPlayerId(Base.java:216)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getPlayerId(Base.java:203)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getFavoriteWarps(Base.java:658)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.user.WarpUser.lambda$new$0(WarpUser.java:30)
[11:49:34 WARN]:        at AxPlayerWarps-1.2.1.jar//com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56)
[11:49:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by AprDeci** [comment]
I had the same problem, which made the plugin almost unusable

**Comment by BenceX100** [comment]
This was fixed in 1.6.0!
