### ISSUE TITLE
Error occurred while enabling AxPlayerWarps v1.1.0 (Is it up to date?)

### ISSUE THREAD

**Issue by TanimsizK** [Artillex-Studios/AxPlayerWarps#4]
I am using paper 1.21.1 #131 fork
[latest.log](https://github.com/user-attachments/files/17831459/latest.log)
I do not have a problem with your other plugins, but there is a problem with this plugin, I am throwing you my entire log file
java version jdk 21 oracle

[16:39:57] [Server thread/ERROR]: Error occurred while enabling AxPlayerWarps v1.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.artillexstudios.axplayerwarps.enums.Sorting.ALPHABETİCAL
	at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.enums.Sorting.valueOf(Sorting.java:3) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.sorting.SortingManager.reload(SortingManager.java:25) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.AxPlayerWarps.enable(AxPlayerWarps.java:122) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.libs.axapi.AxPlugin.onEnable(AxPlugin.java:85) ~[AxPlayerWarps-1.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:39:57] [Server thread/INFO]: [AxPlayerWarps] Disabling AxPlayerWarps v1.1.0
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-214]
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:223)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:199)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:188)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1375)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcStatement.checkClosed(JdbcStatement.java:1273)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1391)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcPreparedStatement.setObject(JdbcPreparedStatement.java:496)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.database.impl.Base.createStatement(Base.java:183)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getWorldId(Base.java:305)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.world.WorldManager.lambda$reload$0(WorldManager.java:17)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[16:39:57] [AxPlayerWarps-Datastore-thread/ERROR]: [com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue] An unexpected error occurred while running ThreadedQueue AxPlayerWarps-Datastore-thread!
java.lang.RuntimeException: World not found!
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.database.impl.Base.getWorldId(Base.java:318) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.world.WorldManager.lambda$reload$0(WorldManager.java:17) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56) ~[AxPlayerWarps-1.1.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-214]
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:223)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:199)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.message.DbException.get(DbException.java:188)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1372)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:286)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.database.impl.Base.createStatement(Base.java:181)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.database.impl.Base.getCategoryId(Base.java:340)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.category.CategoryManager.lambda$reload$0(CategoryManager.java:24)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at AxPlayerWarps-1.1.0.jar//com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56)
[16:39:57] [AxPlayerWarps-Datastore-thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[16:39:57] [AxPlayerWarps-Datastore-thread/ERROR]: [com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue] An unexpected error occurred while running ThreadedQueue AxPlayerWarps-Datastore-thread!
java.lang.RuntimeException: Category not found!
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.database.impl.Base.getCategoryId(Base.java:353) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.category.CategoryManager.lambda$reload$0(CategoryManager.java:24) ~[AxPlayerWarps-1.1.0.jar:?]
	at AxPlayerWarps-1.1.0.jar/com.artillexstudios.axplayerwarps.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56) ~[AxPlayerWarps-1.1.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by BenceX100** [comment]
It seems like you have the wrong "I" character in the word alphabetical in your config, check this part: https://github.com/Artillex-Studios/AxPlayerWarps/blob/main/src/main/resources/config.yml#L90 - changing that should fix this error

**Comment by TanimsizK** [comment]
I'm using default config I didn't make a setting

**Comment by TanimsizK** [comment]
![resim](https://github.com/user-attachments/assets/bc62048d-c60b-4e70-85d6-b25dbdb189a2)
I changed the letter ‘i’ to ‘i’ but got the error again

**Comment by BenceX100** [comment]
Hopefully you could solve this, but if you still would need help please send the entire configuration file or try regenerating it.
